name: Bug Report
description: Reportar um erro ou problema no código
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Por favor, preencha as informações abaixo para que possamos reproduzir e corrigir o problema.
  - type: input
    id: summary
    attributes:
      label: Resumo do problema
      description: Descreva de forma curta o que aconteceu
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Lista clara e numerada dos passos que causam o erro
      placeholder: |
        1. Vá para...
        2. Clique em...
        3. Veja o erro...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      placeholder: O que você esperava que acontecesse?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Se possível, anexe imagens ou vídeos
  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      placeholder: |
        - SO: Linux/Windows/Mac
        - Versão do projeto:
        - Versão do Python/Java/etc:
