blank_issues_enabled: false
contact_links:
  - name: Discussões e Ideias
    url: https://github.com/lari-ember/bioma-vivo/discussions
    about: Use este espaço para trocar ideias que não sejam bugs ou novas features.
